# Generated by Django 4.0.4 on 2022-05-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lk',
            old_name='body',
            new_name='name_lk',
        ),
        migrations.AddField(
            model_name='lk',
            name='email_lk',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lk',
            name='surname_lk',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
