# Generated by Django 4.0.4 on 2022-05-11 09:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facult', models.CharField(default='', max_length=50, verbose_name='Факультет')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('specialty', models.CharField(default='', max_length=50, verbose_name='Специализация')),
                ('salary', models.IntegerField(default=0, verbose_name='Зарплата')),
                ('full_part_time', models.BooleanField(default=False, verbose_name='Занятость')),
                ('work_graph', models.CharField(default='', max_length=20, verbose_name='График работы')),
                ('company', models.CharField(default='', max_length=50, verbose_name='Название компании')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.BigIntegerField(default=0)),
                ('number_of_ratings', models.BigIntegerField(default=0)),
                ('anons', models.CharField(max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(verbose_name='Статья')),
                ('fac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac_FK', to='job.facultet')),
            ],
        ),
        migrations.CreateModel(
            name='Comment_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='job.job')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
