# Generated by Django 4.0.4 on 2022-05-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='email_company',
            field=models.EmailField(default=11, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
